[phases.setup]
nixPkgs = ["nodejs", "glib", "nss", "nspr", "atk", "at-spi2-atk", "cups", "libdrm", "libxkbcommon", "pango", "cairo", "alsa-lib", "mesa", "expat"]

[phases.build]
cmds = [
  "npm install",
  "npx playwright install --with-deps chromium",
  "npm run build"
]
